# Use official Python image
FROM python:3.9

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    BACKEND_API_URL="http://ids_backend:5001" \
    WEBSOCKET_URL="ws://ids_websocket:5003"

# Set working directory
WORKDIR /app

# Copy project files
COPY dashboard/ ./dashboard
COPY config.py requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port for the dashboard
EXPOSE 5002

# Run the Flask Dashboard
CMD ["python", "dashboard/app.py"]
