version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ids_backend
    ports:
      - "5001:5001"
    networks:
      - ids_network
    environment:
      - DATABASE_URL=sqlite:////app/logs/ids_logs.db  # Absolute path for reliability
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}  # Load from .env
    volumes:
      - logs_data:/app/logs
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5001/health"]  # Use container name
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: ids_dashboard
    ports:
      - "5002:5002"
    networks:
      - ids_network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: ids_websocket
    ports:
      - "5003:5003"
    networks:
      - ids_network
    restart: unless-stopped
    environment:
      - SOCKETIO_CORS_ALLOWED_ORIGINS=http://localhost:5002  # Restrict dashboard access
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      backend:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5001/health"]  # Use backend container
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  ids_network:
    driver: bridge

volumes:
  logs_data:
    driver: local
